#!/bin/bash
#

NAME="docker-squid-deb-proxy"
TIME="$(date +%Y%m%d%H%M%S)"
DIR="/tmp/${NAME}-${TIME}"
mkdir -p ${DIR}
echo "using ${DIR} as cache directory"

docker run \
	-h 'squid' --net bridge -m 0b -p 3128:8000 \
	-v ${DIR}:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-e USE_ACL=0 \
	--name ${NAME} \
	--rm \
	muccg/squid-deb-proxy:latest

